### ISSUE TITLE
Issue stopping my game after the last question

### ISSUE THREAD

**Issue by jakemeltzer333** [jakemeltzer333/Back-To-The-Future-Trivia#1]
I am able to cycle through all of my questions and single out whether a players answers correctly or not. My issue is once I get to question 20, when I click on my "next question" button, I get an error in my console. I'm trying to get the game to stop on the last question before I create a results page.

The problem code

```javascript
function createQuestions () {
  console.log('questions created');
  let q = questionCounter;
  $('#question').text(questions[q].question);
  if (q === questions.length - 1) {
      console.log('button removed');
      //$('#next').remove();
    } else {
      $('#question').text(questions[q].question);
    }
```

I tried putting similar code in my different functions and none of them worked. They all returned the same error message.

Links I've looked at:
https://stackoverflow.com/questions/4851027/how-to-stop-a-function-from-running

https://api.jquery.com/queue/

https://www.sitepoint.com/stop-jquery-event-functions/

From the code I attached above, the error message returns "Cannot read property question of undefined." To me, this signals that the game is trying to continue to read the createQuestions function this code is coming from but doesn't realize there are no more questions to create.

When it works, the error message won't pop up and I'll be able to just hit the button and nothing happens on the last question. However, I want to display a results screen after that, so I want the game to start over from there. But I want to take this one step at a time, so I need help with this problem first. Thanks!

**Comment by jlr7245** [comment]
Ok, cool. So, you have two problems. You have what happens in your "else" statement twice -- on ln 136 and on ln 141, so you'd want to remove the first one. Also, because of when you increment the questionCounter, you need to say just `questions.length` instead of `questions.length - 1`.
